/**
 * The relevant triggers 
 */

DROP TRIGGER IF EXISTS ORDER_BEFORE_UT ON ORDERS;
DROP TRIGGER IF EXISTS ORDER_ITEM_BEFORE_UT ON ORDERS;


CREATE OR REPLACE FUNCTION ORDER_BEFORE_UT_FUNC() RETURNS TRIGGER
AS $ORDER_BEFORE_UT$
BEGIN
	
END;
$ORDER_BEFORE_UT$ LANGUAGE plpgsql;


CREATE TRIGGER ORDER_BEFORE_UT BEFORE UPDATE ON ORDERS
FOR EACH ROW
EXECUTE PROCEDURE ORDER_BEFORE_UT_FUNC();

/**
 * 
 */
CREATE OR REPLACE FUNCTION  ORDER_ITEM_BEFORE_UT_FUNC() RETURNS TRIGGER
AS $ORDER_ITEM_BEFORE_UT$
BEGIN
	
END;
$ORDER_ITEM_BEFORE_UT$ LANGUAGE plpgsql;

CREATE TRIGGER ORDER_ITEM_BEFORE_UT BEFORE UPDATE ON ORDERS
FOR EACH ROW
EXECUTE PROCEDURE ORDER_ITEM_BEFORE_UT_FUNC();

/**
 * 
 */
CREATE OR REPLACE FUNCTION INVENTORY_CHANGE_RECORD_BEFORE_UT_FUNC() RETURNS TRIGGER
AS $INVENTORY_CHANGE_RECORD_BEFORE_UT$
BEGIN
	--TODO Check the feasibility for inventory
END ;
$INVENTORY_CHANGE_RECORD_BEFORE_UT$ LANGUAGE plpgsql;

CREATE TRIGGER INVENTORY_CHANGE_RECORD_BEFORE_UT UPDATE ON INVENTORY_CHANGE_RECORDS
FOR EACH ROW
EXECUTE PROCEDURE INVENTORY_CHANGE_RECORD_BEFORE_UT_FUNC();

CREATE OR REPLACE FUNCTION INVENTORY_CHANGE_RECORD_BEFORE_UT_FUNC() RETURNS TRIGGER
AS $INVENTORY_CHANGE_RECORD_BEFORE_UT$
BEGIN
	--TODO Check the feasibility for inventory
END ;
$INVENTORY_CHANGE_RECORD_BEFORE_UT$ LANGUAGE plpgsql;

CREATE TRIGGER INVENTORY_CHANGE_RECORD_BEFORE_UT UPDATE ON INVENTORY_CHANGE_RECORDS
FOR EACH ROW
EXECUTE PROCEDURE INVENTORY_CHANGE_RECORD_BEFORE_UT_FUNC();
